### ISSUE TITLE
Files missing - 'W_ent2rel.json.npy'

### ISSUE THREAD

**Issue by aakashb95** [ansonb/RECON#2]
Hi, thanks for your paper and code. I downloaded the data and have put in ./data/ accordingly. However, I couldn't find these files in your repo. I am running this on colab.
The GAT folder is in the main directory of this code and doesn't contain the missing file. Could you please upload any missing files?
Thanks
```logs
ERROR:root:No list found. [Errno 2] No such file or directory: '../resources/property_blacklist.txt'
ERROR:root:No list found. [Errno 2] No such file or directory: '../../resources/property_blacklist.txt'
ERROR:root:No list found. [Errno 2] No such file or directory: '../resources/property_blacklist.txt'
ERROR:root:No list found. [Errno 2] No such file or directory: '../../resources/property_blacklist.txt'
Traceback (most recent call last):
  File "train.py", line 410, in <module>
    train()
  File "train.py", line 102, in train
    W_ent2rel_all_rels = np.load(w_ent2rel_all_rels_file)
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './models/GAT/WikipediaWikidataDistantSupervisionAnnotations/W_ent2rel.json.npy'
```

**Comment by ansonb** [comment]
Hi,

This is the model file which will be obtained after running the training code in `GAT_sep_space/main.py` on your data.
